### ISSUE TITLE
ICAFIX MCR behavior differs from README

### ISSUE THREAD

**Issue by studentism** [Washington-University/HCPpipelines#126]
My apologies if I'm misunderstanding something here, but based on the ICAFIX README, I expect `${FSL_FIX_MCRROOT}` to be used with FIX's compiled MATLAB functions and `${MATLAB_COMPILER_RUNTIME}` to be used with HCPpipelines compiled MATLAB functions. (According to the **Support for compiled Matlab within specific scripts/hcp_fix_multi_run, ReApplyFixMultiRunPipeline** sub-section, specifically.)

However, hcp_fix_multi_run calls FIX using `${MATLAB_COMPILER_RUNTIME}`.
https://github.com/Washington-University/HCPpipelines/blob/fce2ce895f6c6271768d343af3721e67e5d05769/ICAFIX/hcp_fix_multi_run#L424
Since I have this set to v91, there is a mismatch with FIX's which_mcr.sh script (v93 in my environment).

In practice, I'm not sure how much difference this makes since the Pipeline runs without errors, but I figured I'd mention it since the README goes through the trouble of distinguishing between the two. Thank you in advance for any assistance/guidance here.

**Comment by coalsont** [comment]
`functionhighpassandvariancenormalize` is part of the HCP pipelines, not part of FIX.  It doesn't look like hcp_fix_multi_run calls any FIX-provided matlab functions directly, unlike ReApplyFixMultiRun: https://github.com/Washington-University/HCPpipelines/blob/fce2ce895f6c6271768d343af3721e67e5d05769/ICAFIX/ReApplyFixMultiRunPipeline.sh#L913

**Comment by mharms** [comment]
Right.  In `hcp_fix_multi_run`, `${MATLAB_COMPILER_RUNTIME}` controls the runtime version to use with the `functionhighpassandvariancenormalize` function, which is not part of the FIX distribution itself, and which we (HCP) ourselves compiled and included as part of the HCPpipelines repo.

The actual call to `fix` itself in `hcp_fix_multi_run` is:
https://github.com/Washington-University/HCPpipelines/blob/fce2ce895f6c6271768d343af3721e67e5d05769/ICAFIX/hcp_fix_multi_run#L745

That call to `fix` will source the `settings.sh` file _in the FIX distribution_, which establishes the value for `${FSL_FIX_MCRROOT}`, which must be set appropriately for the particular FIX distribution that you have downloaded (otherwise compiled `fix` itself will not work).

Sorry for the complexity around "FIX", but it is a consequence of the HCPpipelines adding functionality that isn't part of the FIX distribution itself.
