### ISSUE TITLE
Please "release" latest releases (v4.1.2 is listed but v4.0.1 is the "Latest release")

### ISSUE THREAD

**Issue by yarikoptic** [Washington-University/HCPpipelines#162]
FWIW: Could be done by "editing" the tag on https://github.com/Washington-University/HCPpipelines/releases and publishing that release

Thanks in advance!

**Comment by mharms** [comment]
We are working toward that.  As you can see, we identified a couple small bugs in testing since the first version of the 4.1 branch.  Once we confirm that the 4.1.2 tag passes all testing in its QuNex container environment (ongoing), and we can craft an appropriate set of release notes, we will formally publish it as a "Release".

**Comment by yarikoptic** [comment]
Gotcha -- thank you for detailed explanation, feel welcome to close this issue, or close with 4.1.x release being "Released".

**Comment by mharms** [comment]
v4.1.3 is now released.
