### ISSUE TITLE
Questions of T1w/T2w sample spacing calculations

### ISSUE THREAD

**Issue by ManyBookmark** [Washington-University/HCPpipelines#233]
We want to perform “PrefreesurferBatch.sh” with T1w and T2w sample spacing values. Could you please inform me which numbers we need and how to calculate them?

**Comment by mharms** [comment]
It’s the dwell time (interval between points in k-space in the *readout direction), expressed in seconds.

See comments and notes in $HCPPIPEDIR/Examples/Scripts/PreFreeSurferPipelineBatch.sh


--
Michael Harms, Ph.D.
-----------------------------------------------------------
Associate Professor of Psychiatry
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                          Email: ***@***.***

From: ManyBookmark ***@***.***>
Reply-To: Washington-University/HCPpipelines ***@***.***>
Date: Saturday, July 9, 2022 at 6:45 AM
To: Washington-University/HCPpipelines ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Washington-University/HCPpipelines] Questions of T1w/T2w sample spacing calculations (Issue #233)

* External Email - Caution *

We want to perform “PrefreesurferBatch.sh” with T1w and T2w sample spacing values. Could you please inform me which numbers we need and how to calculate them?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWashington-University%2FHCPpipelines%2Fissues%2F233&data=05%7C01%7Cmharms%40wustl.edu%7C3a1fbe9be90349da845208da61a08265%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637929639265982937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2KUcE8zw6%2BLYbwDcFzrG6MM08SxmjcGRiErgYdO9ngU%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA5TABRG6XXKNHJOTTMGNNTVTFQ5FANCNFSM53DIKEEA&data=05%7C01%7Cmharms%40wustl.edu%7C3a1fbe9be90349da845208da61a08265%7C4ccca3b571cd4e6d974b4d9beb96c6d6%7C0%7C0%7C637929639265982937%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5HI0oO8Hzu5PKBZzujbJMyspa0XxCS%2FRzbk%2FyLk44ew%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The materials in this message are private and may contain Protected Healthcare Information or other information of a sensitive nature. If you are not the intended recipient, be advised that any unauthorized use, disclosure, copying or the taking of any action in reliance on the contents of this information is strictly prohibited. If you have received this email in error, please immediately notify the sender via telephone or return mail.
