### ISSUE TITLE
Bugs in PR 259

### ISSUE THREAD

**Issue by glasserm** [Washington-University/HCPpipelines#260]
Looks like PR #259 got merged before I had a chance to look at the outputs.  I see several issues:

1) It seems like we are specifying two kinds of reference myelin maps to the input arguments.  
2) I am hesitant to change the input arguments as dramatically as was done including having "MSMAll" appear in variable names long before the MSMAll Pipeline.  It would be better to stick with the original variable name now accepting a 32k mesh (perhaps it should still also be capable of accepting a 164k mesh as it did before?).  
3) It looks like, again, this was not tested on a fresh directory.
4) There were various scene errors that may be unrelated, but we need to at least try to address.  
5) It would be good to see a diff of the files produced by the old and new code to see what has changed and if we need to make any adjustments.

**Comment by coalsont** [comment]
FYI, pinning an issue is a global thing, it puts it above the issue list for everyone that looks at the issues page.  Having it assigned to you is the main way to personally keep tabs on it.

**Comment by cyang31** [comment]
I see.

**Comment by cyang31** [comment]
@glasserm 
I need some clarifications for the above comments.
- Do we want to keep the old 164k myelin map based _BC processing in GIFTI space?
- If a 164k reference myelin map is specified through `--refmyelinmaps` (equal to `--myelin-target-file`), and when it comes to the MyelinMap_BC processing, do we want to first downsample the 164k reference myelin map to a 32k reference map, which is then fed into the option `--myelin-target-file` in `MyelinMap_BC.sh`? Since the current `MyelinMap_BC.sh` is mainly based on 32k.
- I found why there are some scene errors. The scene errors are the following 
`ERRORS loading scene, output image may be incorrect.
NAME OF FILE: 102311.StrainJ_MSMAll.164k_fs_LR.dscalar.nii
PATH TO FILE: /media/myelin/shared/HCPpipelines_test_rc/comparison1/102311/MNINonLinear
   File was not found
NAME OF FILE: 102311.StrainR_MSMAll.164k_fs_LR.dscalar.nii
PATH TO FILE: /media/myelin/shared/HCPpipelines_test_rc/comparison1/102311/MNINonLinear
   File was not found`
which are files after MSMAll processed. However, after pipelines PreFreeSurfer+FreeSurfer+PostFreeSurfer (RegName="MSMSulc"), the Strain_J_MSMAll and Strain_R_MSMAll are not generated yet but they are showing up in the template scene file `global/templates/StructuralQC/TEMPLATE_structuralQC.scene`. 
- I created two fresh directories, and checked the diff of the directory tree structure. The files that are created by the **old** script but **NOT** by the **new** script are 
   - MNINonLinear/Native/102311.L.RefMyelinMap.native.func.gii
   - MNINonLinear/Native/102311.R.RefMyelinMap.native.func.gii
- The files that are created by the **new** script but **NOT** by the **old** script are 
   - MNINonLinear/fsaverage_LR32k/102311.BiasField.32k_fs_LR.dscalar.nii
   - MNINonLinear/Native/102311.BiasField.native.dscalar.nii

I don't see this difference as an issue, but you would prefer to match them to the **old** setting, I can remove the new files and try to generate the RefMyelinMap in native space.

**Comment by glasserm** [comment]
*No we want to replace that code block.
*Yes that is correct.
* @mharms
*Let's create these files anyway.
*What BiasField files is the old script creating?

**Comment by mharms** [comment]
>     * @mharms
>       *Let's create these files anyway.
>       *What BiasField files is the old script creating?

What is this referring to?

**Comment by mharms** [comment]
I wouldn't suppress notification of missing files from a scene entirely, but labeling it a "WARNING" rather than an "ERROR" seems like it might be appropriate.

**Comment by coalsont** [comment]
For the common case of loading/capturing a scene, a missing file is definitely an error.  In fact, I would lean towards having it not generate the output image when files are missing, unless an extra option of something like `-allow-missing-files` were specified.

Regardless, that is a workbench message, not a pipelines message, so the pipelines could hide it, but it isn't appropriate for the pipelines to alter the message.  We could use redirection to suppress a message that we expect to happen, to avoid spooking the user, but that would also hide any additional messages from that command, which might contain other things that are wrong.

**Comment by mharms** [comment]
I thought we *were* talking about a workbench message, not a pipelines message...

**Comment by coalsont** [comment]
Since this is the pipelines issue page, I was assuming those error messages resulted from a `wb_command -show-scene` command somewhere in the pipelines.  If we are talking wb_view, then the error message logic should stay as-is, because it is absolutely correct for missing files to be reported as an error, given no information about who thinks which files are okay to be missing.

**Comment by glasserm** [comment]
Right, I thought this was a bug.  I don't think scenes have a good concept of files that are "sometimes okay to be missing."

**Comment by mharms** [comment]
Well, in this case at least, it is ok for those particular files to be missing until MSMAll is run.  As a practical matter, I don't see what we would do differently.

**Comment by mharms** [comment]
I'm not interested in spending time coding up a "fix" for this, which would be a lot of work for something is that not a problem, IMO.

**Comment by glasserm** [comment]
That was why I suggested suppressing the error messages from those lines.

**Comment by coalsont** [comment]
If the pipelines run a `wb_command -show-scene` and we redirect its stderr to suppress those expected messages, but other files are also missing, then those errors will also be hidden during that command, and the images will be wrong without producing a visible error message.  If we aren't going to fix it the right way (make a "before-MSMAll" scene that doesn't error), hiding the error we aren't willing to fix is in the territory of "the wrong way".

Instead of hiding anything, we can output a message that says "errors that mention filenames containing '_MSMAll' can be ignored", which I would consider to be "less wrong".  We could even have the script check for the existence of some '_MSMAll' file, and only show this message when it isn't present.

**Comment by glasserm** [comment]
That's fine.  I just expect the HCP Pipelines to run without error.
