### ISSUE TITLE
gradient coefficient file

### ISSUE THREAD

**Issue by saraoanu** [Washington-University/HCPpipelines#51]
The email provided for getting the gradient coefficient file for gradient correction is not valid. can you provide an alternative?

**Comment by tbbrown** [comment]
Thank you for pointing out that an email provided in our documentation is invalid.

We are not authorized to share any gradient coefficient files. These are considered proprietary information of the scanner manufacturers. You will need to contact a representative of your scanner manufacturer and ask for a gradient coefficients file.

Since the email address to which you refer is invalid, I would like to remove it from our documentation. However, I'm not immediately able to find the location in our documentation where that email address is cited. Could you please point me to where it is? Is it somewhere within the Wiki documentation for the HCP Pipelines? My apologies if it is "hiding in plain sight", and I should easily see it. Thank you.

**Comment by saraoanu** [comment]
That's ok. Email address is in FAQ's 7 or 8

**Comment by mharms** [comment]
I think that the Siemen's contact provided in FAQ 7 was updated, and is now appropriate, so closing this issue.
